//
//  MockData.swift
//  MoviesAppTests
//
//  Created by Reyhan Rifqi Azzami on 17/06/22.
//

import Foundation
@testable import MoviesApp
struct MockData{
    static let movies = [
        Movie(id: 338953, overview: "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/8ZbybiGYe8XM4WGmGlhF0ec5R7u.jpg")!, releaseDate: "2022-04-06", title: "Fantastic Beasts: The Secrets of Dumbledore", video: false, voteAverage: 6.9, voteCount: 1777),
        Movie(id: 675353, overview: "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg")!, releaseDate: "2022-03-30", title: "Sonic the Hedgehog 2", video: false, voteAverage: 7.8, voteCount: 2045),
        Movie(id: 610150, overview: "The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/rugyJdeoJm7cSJL1q4jBpTNbxyU.jpg")!, releaseDate: "2022-06-11", title: "Dragon Ball Super: Super Hero", video: false, voteAverage: 6.8, voteCount: 13),
        Movie(id: 634649, overview: "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg")!, releaseDate: "2021-12-15", title: "Spider-Man: No Way Home", video: false, voteAverage: 8.1, voteCount: 13514),
        Movie(id: 453395, overview: "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg")!, releaseDate: "2022-05-04", title: "Doctor Strange in the Multiverse of Madness", video: false, voteAverage: 7.4, voteCount: 2272),
        Movie(id: 335787, overview: "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg")!, releaseDate: "2022-02-10", title: "Uncharted", video: false, voteAverage: 7.1, voteCount: 2415),
        Movie(id: 414906, overview: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg")!, releaseDate: "2022-03-01", title: "The Batman", video: false, voteAverage: 7.8, voteCount: 5156),
        Movie(id: 508947, overview: "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.", posterPath: URL(string:"https://image.tmdb.org/t/p/w500/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg")!, releaseDate: "2022-03-10", title: "Turning Red", video: false, voteAverage: 7.5, voteCount: 2455),
    ]

    static let review = [
        Review(author: "RADIO1'S MR. MOVIE!-MAD AMI 🌠", content: "If, ( -like yours truly- ), you've been a Loyal, Loving Adorer of the web-slinger for ( pretty much ) your -Entire- life . . . bring TWICE the amount of tissues ; 1 half for the ( -Several- ) Ribtickling 'Funnies' in NWH, & the other half for the **richly soulful & -{ FABULOUSLY HUMAN }- emotional scenes** that you are unquestionably going to encounter.  Also, -Do- try & stay till the -Very- end of the movie, for not just 1, but in fact, -2- great teaser scenes . . . as you'll be -certain- to glean a few -exciting- insights into the near future of the MCU ( Marvel Cinematic Universe ). And here, without further ado, is my final appraisal of Spider-Man: No Way Home, Marvel's truly \"fresh\", and -{ Uplifting }- New Multiplex-Marvel. **", id: "61bbe57fd2f5b5006119efff", url: "https://www.themoviedb.org/review/61bbe57fd2f5b5006119efff"),
        Review(author: "Chris Sawin", content: "_Spider-Man: No Way Home_ isn’t without its flaws, but it is mostly exactly what it’s advertised to be. The film doesn’t necessarily redefine the, “With great power comes great responsibility,” aspect for Tom Holland’s Spider-Man, but it without a doubt gives the MCU version of Spider-Man his version of that principle.", id: "61be4ad9c7176d0060507dc9", url: "https://www.themoviedb.org/review/61be4ad9c7176d0060507dc9"),
        Review(author: "T D Heath", content: "Long awaited and very conspiricized, **'Spider-man:No way Home'** Lives up and surpasses hype, The introduction of charcters once thought cordened off into the MCU, came both as a shock and as an eventual certainty. The Pleathora of indephth easter eggs creates awonderful viewing for the spider-man fan but alienates the casual none MCU fanatic viewers. The plot is dense not in fault but in advantage, it crams in expectation with suitable comedy and light heartedness. The director created a a comprehensive journey of emotion with several troughs and many peaks leaving a sense of WOAH at the end", id: "61bee9b9d371970066b9cf85", url: "https://www.themoviedb.org/review/61bee9b9d371970066b9cf85"),
        Review(author: "sauceopet", content: "Best spider man movie I have ever seen. Literally got chills watching it cinema hall. Cinema hall turned into stadium. The screams, the excitement, the hype - all about it is amazing in it's own way. A total fan service.", id: "61cd6119a097dc001c3dd6b3", url: "https://www.themoviedb.org/review/61cd6119a097dc001c3dd6b3"),
        Review(author: "r96sk", content: "Onto what we see onscreen. The plot is great and I wouldn't change anything about it, there is one or two things that I had question marks about whilst watching but those quickly dissipated. The pacing is top notch and the music is superb, the respective screen times of everybody was pinpoint and, along with the already noted humour, the film also packs a punch on a more serious level to boot. This really is top tier Marvel! Would watch again, would recommended etc. Awesome!", id: "61d7cd03a58902008b976594", url: "https://www.themoviedb.org/review/61d7cd03a58902008b976594"),
        Review(author: "Adriano", content: "This is the perfect Marvel movie that isn't an Avengers film. It pays off everything thing it builds up, corrects previous misgivings and really gets the character of Spider-Man right. All while setting things up in an interesting way that it's bound to be fresh next time out. Absolutely loved this.", id: "61d872c5c669ad00904a2397", url: "https://www.themoviedb.org/review/61d872c5c669ad00904a2397"),
        Review(author: "JPV852", content: "Good addition to the Spider-Man franchise and a quasi-reset. Fun seeing the old guard in here with Maguire and Garfield along with their foes and at least their inclusions didn't feel as forced as I feared when this movie was first announced. The relationship between Tom Holland and Zendaya worked better than in Homecoming and even Far From Home. Will be interesting to see where the series goes from here. **4.0/5**", id: "62588a74c92c5d00652ee366", url: "https://www.themoviedb.org/review/62588a74c92c5d00652ee366"),
    ]

    static let videos = [
        Video(name: "Special Features Preview", key: "19pkBDAWPE8", site: "YouTube", id: "62166f190bb0760043053859"),
        Video(name: "Walking Corpses Clip", key: "GGe_h2MWMrs", site: "YouTube", id: "61f77629bb105700a0b16a3f"),
        Video(name: "Mirror Dimension Clip", key: "Bh8NeyejykU", site: "YouTube", id: "61d66132e194b000414703fc"),
        Video(name: "Behind-The-Scenes", key: "aC40LnWR9TE", site: "YouTube", id: "61d662809defda008d03088c"),
        Video(name: "Spider Bite", key: "M6ix8Q50OaM", site: "YouTube", id: "61a4c0f30231f20061539241"),
        Video(name: "Official IMAX® Trailer", key: "pBvH8hvnJPk", site: "YouTube", id: "61982e61e2ff32004371953a"),
        Video(name: "Official Trailer", key: "JfVOs4VSpmA", site: "YouTube", id: "61945b8a4da3d4002992d5a6"),
        Video(name: "Official Teaser Trailer", key: "WgU7P6o-GkM", site: "YouTube", id: "6124694a534661005cd0b8a7"),
        Video(name: "The New Spider-Man Title is…", key: "iqyPvdsOWKk", site: "YouTube", id: "60378fdcd132d60040a45d96"),
    ]
}
